services:
  project:
    build:
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    dns:
        - 8.8.8.8
        - 1.1.1.1
    environment:
      SERVER_NAME: ":80"
      DEV_PORT: 80
    depends_on:
      project-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dev-o10r-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.project_https.rule=Host(`project.o10r.io`)
      - traefik.http.routers.project_https.tls=true
      - traefik.http.routers.project_https.entrypoints=https
    volumes:
      - ./:/app
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/var/www/.composer
      - caddy_data:/data
      - caddy_config:/config
      - ./xdebug.ini:/etc/php/conf.d/xdebug-enable.ini
    tty: true
  project-db:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306"
    volumes:
      - ppDatabase:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=secret
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - dev-o10r-network
  project-cache:
    restart: unless-stopped
    networks:
      - dev-o10r-network
    image: redis:latest
  project-cache-view:
    image: robinn/phpcacheadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.cache_https.rule=Host(`project-cache.o10r.io`)
      - traefik.http.routers.cache_https.tls=true
      - traefik.http.routers.cache_https.entrypoints=https
    environment:
      - PCA_REDIS_0_HOST=project-cache
      - PCA_REDIS_0_PORT=6379
    networks:
      - dev-o10r-network
    restart: unless-stopped
    links:
      - project-cache

volumes:
  ppDatabase:
  caddy_data:
  caddy_config:

networks:
  dev-o10r-network:
   name: dev-o10r-network
   external: true
