services:
  project:
    build:
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      SERVER_NAME: ":80"
      DEV_PORT: 80
    restart: unless-stopped
    networks:
      - dev-o10r-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.project_https.rule=Host(`project.o10r.io`)
      - traefik.http.routers.project_https.tls=true
      - traefik.http.routers.project_https.entrypoints=https
    volumes:
      - ./:/app
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/var/www/.composer
      - caddy_data:/data
      - caddy_config:/config
      - ./xdebug.ini:/etc/php/conf.d/xdebug-enable.ini
    healthcheck:
        test: [ "sh", "[ -f /app/vendor/autoload.php ] || exit 1" ]
        interval: 5s
        retries: 20
        start_period: 5s
    tty: true
  project-db:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306"
    volumes:
      - ppDatabase:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=secret
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - dev-o10r-network
  project-migrate:
      build:
        target: dev
        args:
          UID: ${UID:-1000}
          GID: ${GID:-1000}
      env_file:
          - .env
      environment:
        YII_ENV: prod
        YII_DEBUG: false
      volumes:
          - ./:/app
      depends_on:
          project-db:
              condition: service_healthy
          project:
              condition: service_healthy
      entrypoint: php yii migrate:up -q
      networks:
          - dev-o10r-network

volumes:
  ppDatabase:
  caddy_data:
  caddy_config:

networks:
  dev-o10r-network:
   name: dev-o10r-network
   external: true
